Dynamically choose interface number
webusb/arduino pull request #54
Opened 2018-10-25 04:05 UTC by jpliew

The current `serial.js` assumed all WebUSB device has an interface number of 2, in endpoint of 5 and out endpoint of 4, hard coded.

This is correct if the device is just acting as WebUSB alone. When a device has a few other interfaces, the WebUSB interface might not be on interface number 2.

This pull request will loop through the `this.device_` and detect a class of 0xFF (I can't find any other differentiation for other device interface other than this to guess if the interface is WebUSB), loop through the endpoints and get the correct interface number, ID for in and out endpoints .

Hope this helps.

Cheers
JP

2018-10-25 04:30 UTC, jpliew commented
Tested with ATmega32U4 compatible board with 
- Windows 8.1 - Chrome Version 69.0.3497.100 (Official Build) (64-bit)
- Windows 10 - Chrome Version 70.0.3538.77 (Official Build) (64-bit)

2018-11-06 01:47 UTC, reillyeon requested changes
Thanks for this contribution. Just a couple things before we merge this:

1. Remove console.log statements that were added for debugging. If you want to add some diagnostic logging then I suggest a single log message that prints out the interface and endpoint numbers that are being used when the device is opened.

2. Since these values may vary from device to device please keep them in the Port object rather than as globals.

2018-11-06 02:25 UTC, jpliew commented
Done.

2018-11-06 23:25 UTC, reillyeon commented on demos/serial.js
> +  var endpointOut=4;			// original out endpoint ID of WebUSB Arduino demo
Please move these variables into fields on the `Port` object. These are still shared between all instances rather than being per-device.

2018-11-12 23:07 UTC, jpliew commented on demos/serial.js
> +  var endpointOut=4;			// original out endpoint ID of WebUSB Arduino demo
Should be good now. Please check.

2018-11-15 01:33 UTC, reillyeon approved these changes

2018-11-15 01:36 UTC, merged